version: '3'

services:
  api-demo:
    container_name: api-demo
    ports: 
      - "8700:8700" 
    build:
      context: ../src
      dockerfile: ../devops/Dockerfile
      args:
        name: ObservabilityDemo.Api
        port: 8700

  internal-api-demo:
    container_name: internal-api-demo
    ports: 
      - "8701:8701" 
    build:
      context: ../src
      dockerfile: ../devops/Dockerfile
      args:
        name: ObservabilityDemo.InternalApi
        port: 8701

  mongodb:
    image: mongo:3.6.20-xenial
    container_name: mongodb
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: MongoAuth