version: '3'

services:
  api-demo:
    container_name: api-demo
    ports: 
      - "8700:8700" 
    build:
      context: ../src
      dockerfile: ../devops/Dockerfile
      args:
        name: ObservabilityDemo.Api
        port: 8700
    environment:
      CORECLR_ENABLE_PROFILING: 1
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: 1
      NEW_RELIC_APP_NAME: "ObservabilityDemo.Api 1"
      NEW_RELIC_LICENSE_KEY: "${NR_LICENSE}"
    links:
      - mongodb
      - internalapidemo
    depends_on:
      - mongodb
      - internalapidemo

  internalapidemo:
    container_name: internalapidemo
    ports: 
      - "8701:8701" 
    build:
      context: ../src
      dockerfile: ../devops/Dockerfile
      args:
        name: ObservabilityDemo.InternalApi
        port: 8701
    environment:
      CORECLR_ENABLE_PROFILING: 1
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: 1
      NEW_RELIC_APP_NAME: "ObservabilityDemo.InternalApi 1"
      NEW_RELIC_LICENSE_KEY: "${NR_LICENSE}"
      NR_LICENSE: "${NR_LICENSE}"

  mongodb:
    image: mongo:3.6.20-xenial
    container_name: mongodb
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: MongoAuth