version: '3'

services:
  apidemotdc:
    container_name: apidemotdc1
    ports: 
      - "8700:8700" 
    build:
      context: ../src
      dockerfile: ../devops/Dockerfile
      args:
        name: ObservabilityDemo.Api
        port: 8700
    environment:
      CORECLR_ENABLE_PROFILING: 1
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: 1
      NEW_RELIC_APP_NAME: "ObservabilityDemo.Api TDC 1"
      NEW_RELIC_LICENSE_KEY: "${NR_LICENSE}"
    links:
      - mongodb
      - internalapidemotdc1
    depends_on:
      - mongodb
      - internalapidemotdc1

  internalapidemotdc1:
    container_name: internalapidemotdc1
    ports: 
      - "8701:8701" 
    build:
      context: ../src
      dockerfile: ../devops/Dockerfile
      args:
        name: ObservabilityDemo.InternalApi
        port: 8701
    environment:
      CORECLR_ENABLE_PROFILING: 1
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: 1
      NEW_RELIC_APP_NAME: "ObservabilityDemo.InternalApi TDC 1"
      NEW_RELIC_LICENSE_KEY: "${NR_LICENSE}"

  mongodb:
    image: mongo:3.6.20-xenial
    container_name: mongodb
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: MongoAuth